version: '3'

services:
  postgres_db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
      # - python home_db/manage.py migrate
      # - python home_db/manage.py runserver 0.0.0.0:8000
      # command: python home_db/manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/home_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db